[C++23] bsdiff: Add missing header
Add <sys/types.h> for off_t because C++23 removed certain transitive
includes

Error:
external/bsdiff/include/bsdiff/decompressor_interface.h:36:59: error:
unknown type name 'off_t'
   36 |                                                           off_t
offset,

Generated by Gemini.

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m libbspatch
Change-Id: I51a6d140a5a0bca9c87bd752e01369f2fb912dfc